import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col gap-5 w-full items-center mt-10 justify-center`}
      >
        {children}
        <div className="flex justify-center gap-10 items-center w-full">
          {team}
          {analytics}
        </div>
      </body>
    </html>
  );
}
