import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  analytics: React.ReactNode;
  teams: React.ReactNode;
  // login: React.ReactNode;
  // dashboard: React.ReactNode;
}) {
  // const getUser = () => {
  //   const signedIn = false;
  //   return signedIn;
  // };
  // const isLoggedIn = getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        {props.children}
        {props.teams}
        {props.analytics}
        {/* {isLoggedIn ? props.dashboard : props.login} */}
      </body>
    </html>
  );
}
